export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_UPLOAD_IMAGE_REQUEST = 'PRODUCT_UPLOAD_IMAGE_REQUEST'
export const PRODUCT_UPLOAD_IMAGE_SUCCESS = 'PRODUCT_UPLOAD_IMAGE_SUCCESS'
export const PRODUCT_UPLOAD_IMAGE_FAIL = 'PRODUCT_UPLOAD_IMAGE_FAIL'

export const PRODUCT_BEST_SELLER_REQUEST = 'PRODUCT_BEST_SELLER_REQUEST'
export const PRODUCT_BEST_SELLER_SUCCESS = 'PRODUCT_BEST_SELLER_SUCCESS'
export const PRODUCT_BEST_SELLER_FAIL = 'PRODUCT_BEST_SELLER_FAIL'

export const PRODUCT_NEW_ARRIVAL_REQUEST = 'PRODUCT_NEW_ARRIVAL_REQUEST'
export const PRODUCT_NEW_ARRIVAL_SUCCESS = 'PRODUCT_NEW_ARRIVAL_SUCCESS'
export const PRODUCT_NEW_ARRIVAL_FAIL = 'PRODUCT_NEW_ARRIVAL_FAIL'

export const PRODUCT_FREATURED_REQUEST = 'PRODUCT_FREATURED_REQUEST'
export const PRODUCT_FREATURED_SUCCESS = 'PRODUCT_FREATURED_SUCCESS'
export const PRODUCT_FREATURED_FAIL = 'PRODUCT_FREATURED_FAIL'