import React from 'react'
import BreadCrumb from '../components/BreadCrumb'
import logo from '../img/svg/logo-dark-blue.svg'

const AboutPage = () => {
    return (
        <div className="container py-5">
            <BreadCrumb/>
            <p className="mb-3 fs-3">About Us</p>
            <div className="my-5">
                <img src={logo} alt="logo" />
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem voluptates quisquam culpa ad expedita, aliquid rerum, vero nihil voluptas, minima deleniti delectus sint doloribus enim. Perspiciatis accusantium commodi ratione! Minima facere laudantium explicabo necessitatibus exercitationem aliquid consequuntur non minus. Blanditiis, laborum quo itaque a temporibus officiis voluptas expedita beatae illum aliquid natus eveniet reiciendis aspernatur molestias hic optio culpa repellendus, debitis, unde facilis quia. Adipisci numquam laboriosam iusto? Et neque, mollitia, vero quidem esse exercitationem libero recusandae temporibus facere ex dolor totam quae voluptatibus qui velit dicta voluptate quia aliquam commodi. Vitae dolore architecto, explicabo praesentium, facilis provident natus dolor perspiciatis, delectus culpa cum! Ea vel tempora incidunt unde sed architecto dignissimos voluptatum consectetur id, necessitatibus earum culpa aperiam dicta laborum eligendi itaque hic est eum laudantium rerum adipisci recusandae voluptas officia obcaecati. Non ad est id enim odio accusamus rerum aliquid maxime repellendus ipsam molestiae perferendis qui, aspernatur quo veritatis eos deserunt, asperiores voluptate tenetur iusto, sint accusantium. Culpa sed cum pariatur laborum, magnam similique odit fuga praesentium quis, nemo itaque! Veniam aperiam soluta ex, molestias exercitationem sapiente beatae impedit vero voluptatem? Molestiae veritatis dolorum dolore, nemo dolores facere accusantium, soluta, excepturi quia deleniti maxime laudantium 
                <br /><br />
                quae nam dignissimos! Quaerat consequuntur veniam eum vitae, eos nostrum dolore, repellendus rerum magni quas nam modi sequi facere blanditiis veritatis amet eligendi alias ullam ex. Adipisci deserunt iusto illo molestias facere nam. Officia sint veritatis magni dicta officiis quasi culpa eveniet soluta iusto doloribus delectus ab dolorem sapiente voluptas neque eius quod animi voluptatibus, esse eum tempore recusandae consequuntur cumque? Nam recusandae eligendi ipsa dignissimos, neque quod doloremque adipisci quas culpa aperiam? Labore dolorum provident vitae perferendis optio sapiente quaerat vel quasi tenetur culpa beatae impedit, deleniti minus voluptatem non voluptatum repellat porro nobis laudantium numquam architecto animi. Placeat ipsam omnis fugiat autem dolores velit, architecto, nemo adipisci illum, temporibus repellendus. Pariatur omnis vel quod temporibus tenetur expedita excepturi quidem obcaecati illo illum non, fugiat soluta? Quasi id, est maiores nisi ab consequatur necessitatibus deserunt quaerat voluptates esse. Nulla velit consectetur <br/><br/>placeat quis ipsa perferendis omnis corporis sapiente et quibusdam minus assumenda commodi iure quaerat, neque autem reprehenderit illum vero perspiciatis dolores ipsum. Minima inventore quam possimus modi sequi repudiandae labore cum delectus dolorum, temporibus, tenetur maiores quas repellat? Aut alias veritatis nesciunt consequuntur laboriosam, illum inventore id, voluptate, architecto consequatur illo sunt omnis vero! Sit nobis numquam eos asperiores culpa. Quia nemo minima placeat, corrupti illum quibusdam reprehenderit dolore! Ea sapiente eos veritatis similique nostrum modi delectus, laborum facere excepturi quisquam incidunt quis nihil voluptate laboriosam pariatur sit culpa eaque esse mollitia inventore quos ex vero. Numquam quaerat tenetur recusandae earum nesciunt ab iste quisquam minima eaque modi! Ex quos temporibus, suscipit iste voluptatem expedita eos, ea totam quasi reiciendis officiis ipsam. Odio dolorum vero sint adipisci quo voluptate porro ab explicabo ea repudiandae? Consequatur explicabo ut doloremque soluta dolor eligendi, animi cumque architecto aliquam et eius, vero, illo modi. Iure, ex voluptate enim atque quasi sequi dolore tempora asperiores blanditiis.</p>
        </div>
    )
}

export default AboutPage
